version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/adaptive-math-backend:latest
    container_name: adaptive_learning_backend
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    restart: always 
